spring:
  application:
    name: backend
  main:
    banner-mode: off
  data:
    mongodb:
      uri: mongodb+srv://harsha:WBAj99YUJ0PdoacT@harsha.xastq.mongodb.net/?retryWrites=true&w=majority&appName=Harsha
      database: typeface
      auto-index-creation: true
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB

file:
  upload-dir: uploads