spring:
  application:
    name: backend
  main:
    banner-mode: off
  data:
    mongodb:
      host: localhost
      port: 27017
      database: typeface
      auto-index-creation: true

file:
  upload-dir: uploads